--CRIANDO BANCO DE DADOS
create database SUCOS_VENDAS

--CRIANDO A TABELA DE CLIENTES
CREATE TABLE [TABELA DE CLIENTES]
(
	[CPF] [varchar](11),
	[NOME][VARCHAR](100),
	[ENDERECO 1][VARCHAR](150),
	[ENDERECO 2][VARCHAR](150),
	[BAIRRO][VARCHAR](50),
	[CIDADE][VARCHAR](50),
	[ESTADO][VARCHAR](2),
	[CEP][VARCHAR](8),
	[DATA DE NASCIMENTO][DATE],
	[IDADE][SMALLINT],
	[SEXO][VARCHAR](1),
	[LIMITE DE CREDITO][MONEY],
	[VOLUME DE COMPRA][FLOAT],
	[PRIMEIRA COMPRA][BIT]
)

--CRIANDO TABELA DE VENDEDORES
CREATE TABLE [TABELA DE VENDEDORES]
(
[MATRICULA] [VARCHAR](5),
[NOME][VARCHAR](100),
[PERCENTUAL COMISSAO][FLOAT]
)

--EXCLUSAO DE TABELA
DROP TABLE [dbo].[TABELA DE VENDEDORES 02]

--incluindo produto
INSERT INTO [dbo].[TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
 [NOME DO PRODUTO],
 [EMBALAGEM],
 [TAMANHO],
 [SABOR],
 [PRECO DE LISTA])
VALUES
('1040107',
'Light - 350 ml - Melancia',
'Lata',
'350 ml',
'Melância',
4.56);

--incluindo vendedor
INSERT INTO dbo.[TABELA DE VENDEDORES]
(MATRICULA,
NOME,
[PERCENTUAL COMISSAO])
VALUES
('00233',
'José Geraldo da Fonseca',
0.10)

--incluindo produtos ao mesmo tempo
INSERT INTO [dbo].[TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
 [NOME DO PRODUTO],
 [EMBALAGEM],
 [TAMANHO],
 [SABOR],
 [PRECO DE LISTA])
VALUES
('1037797',
'Clean - 2 Litros - Laranja',
'PET',
'2 Litros',
'Laranja',
16.01);

INSERT INTO [dbo].[TABELA DE PRODUTOS]
([CODIGO DO PRODUTO],
 [NOME DO PRODUTO],
 [EMBALAGEM],
 [TAMANHO],
 [SABOR],
 [PRECO DE LISTA])
VALUES
('1000889',
'Sabor da Montanha - 700 ml - Uva',
'Garrafa',
'700 ml',
'Uva',
6.31);



--incluindo vendedores ao mesmo tempo
INSERT INTO dbo.[TABELA DE VENDEDORES]
(MATRICULA,
NOME,
[PERCENTUAL COMISSAO])
VALUES
('00235',
'Márcio Almeida Silva',
0.08);

INSERT INTO dbo.[TABELA DE VENDEDORES]
(MATRICULA,
NOME,
[PERCENTUAL COMISSAO])
VALUES
('00236',
'Cláudia Morais',
0.08)

-- ATUALIZACAO DE PRODUTO

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Lata', [PRECO DE LISTA] = 2.46
WHERE [CODIGO DO PRODUTO] = '544931'

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Garrafa'
WHERE [CODIGO DO PRODUTO] = '1078680'

--atualizacao de vendedores

UPDATE [TABELA DE VENDEDORES]
SET [PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00238'

UPDATE [TABELA DE VENDEDORES]
SET [NOME] = 'José Geraldo da Fonseca Júnior'
WHERE [MATRICULA] = '00233'

--EXCLUSAO DE PRODUTO

 DELETE FROM [SUCOS_VENDAS].[dbo].[TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO] = 1088126

--EXCLUSAO DE VENDEDORES
 DELETE FROM [SUCOS_VENDAS].[dbo].[TABELA DE VENDEDORES]
WHERE [MATRICULA] = '00233'	

--REMOVENDO PROPRIEDADE DE NULO PARA NAO NULO
ALTER TABLE [TABELA DE PRODUTOS]
ALTER COLUMN [CODIGO DO PRODUTO]
VARCHAR(10) NOT NULL


--ADICIONANDO CHAVE PRIMARIA
ALTER TABLE [TABELA DE PRODUTOS]
ADD CONSTRAINT PK_PRODUTOS 
PRIMARY KEY CLUSTERED --ADICIONANDO UMA CHAVE PRIMARIA
([CODIGO DO PRODUTO])  --CAMPO PARA CHAVE PRIMARIA

--VENDEDORES
--REMOVENDO PROPRIEDADE DE NULO PARA NAO NULO
ALTER TABLE [TABELA DE VENDEDORES]
ALTER COLUMN [MATRICULA]
VARCHAR(5) NOT NULL


--ADICIONANDO CHAVE PRIMARIA
ALTER TABLE [TABELA DE VENDEDORES]
ADD CONSTRAINT PK_VENDEDORES
PRIMARY KEY CLUSTERED --ADICIONANDO UMA CHAVE PRIMARIA
([MATRICULA])  --CAMPO PARA CHAVE PRIMARIA

--ALTERANDO A COLUNA CPF
ALTER TABLE [TABELA DE CLIENTES]
ALTER COLUMN [CPF]
VARCHAR(11) NOT NULL

--ADICIONANDO CHAVE PRIMARIA
ALTER TABLE [TABELA DE CLIENTES]
ADD CONSTRAINT PK_CLIENTES 
PRIMARY KEY CLUSTERED ([CPF])



--ADICIONANDO CLIENTE
INSERT INTO [dbo].[TABELA DE CLIENTES]
           ([CPF]
           ,[NOME]
           ,[ENDERECO 1]
           ,[ENDERECO 2]
           ,[BAIRRO]
           ,[CIDADE]
           ,[ESTADO]
           ,[CEP]
           ,[DATA DE NASCIMENTO]
           ,[IDADE]
           ,[SEXO]
           ,[LIMITE DE CREDITO]
           ,[VOLUME DE COMPRA]
           ,[PRIMEIRA COMPRA])
     VALUES
           ('00000000001'
           ,'JOÃO DA SILVA'
           ,'RUA 10'
           ,''
           ,'CENTRO'
           ,'RIO DE JANEIRO'
           ,'RJ'
           ,'21000000'
           ,'1990-10-25'
           ,31
           ,'M'
           ,120000.50
           ,1000
           ,1)


--ADICIONANDO COLUNAS EM VENDEDORES
ALTER TABLE [TABELA DE VENDEDORES]
ADD [DATA ADMISSAO]
DATE NULL

ALTER TABLE [TABELA DE VENDEDORES]
ADD [DE FERIAS]
BIT NULL	

--REMOVENDO TABELA DE VENDEDORES
DROP TABLE [TABELA DE VENDEDORES]

--RE CRIANDO TABELA DE VENDEDORES
CREATE TABLE [TABELA DE VENDEDORES]
(
[MATRICULA] [VARCHAR](5),
[NOME][VARCHAR](100),
[PERCENTUAL COMISSAO][FLOAT],
[DATA ADMISSAO] [DATE],
[DE FERIAS] [BIT]
)


--ADICIONANDO REGISTROS DE COLUNAS NOVAS
INSERT INTO [dbo].[TABELA DE VENDEDORES]
           ([MATRICULA]
           ,[NOME]
           ,[PERCENTUAL COMISSAO]
           ,[DATA ADMISSAO]
           ,[DE FERIAS])
     VALUES
           ('00235'
           ,'Márcio Almeida Silva'
           ,0.08
           ,'2014-05-15'
           ,0)

		   INSERT INTO [dbo].[TABELA DE VENDEDORES]
           ([MATRICULA]
           ,[NOME]
           ,[PERCENTUAL COMISSAO]
           ,[DATA ADMISSAO]
           ,[DE FERIAS])
     VALUES
           ('00236'
           ,'Cláudia Morais'
           ,0.08
           ,'2013-09-17'
           ,1)


		   INSERT INTO [dbo].[TABELA DE VENDEDORES]
           ([MATRICULA]
           ,[NOME]
           ,[PERCENTUAL COMISSAO]
           ,[DATA ADMISSAO]
           ,[DE FERIAS])
     VALUES
           ('00237'
           ,'Roberta Martins'
           ,0.11
           ,'2017-03-18'
           ,1)

		   INSERT INTO [dbo].[TABELA DE VENDEDORES]
           ([MATRICULA]
           ,[NOME]
           ,[PERCENTUAL COMISSAO]
           ,[DATA ADMISSAO]
           ,[DE FERIAS])
     VALUES
           ('00238'
           ,'Pericles Alves'
           ,0.11
           ,'2016-08-21'
           ,0)

		   
		   
/*AULA 5*/
--CONSULTANDO NA TABELA
SELECT [CPF]
      ,[NOME]
      ,[ENDERECO 1]
      ,[ENDERECO 2]
      ,[BAIRRO]
      ,[CIDADE]
      ,[ESTADO]
      ,[CEP]
      ,[DATA DE NASCIMENTO]
      ,[IDADE]
      ,[SEXO]
      ,[LIMITE DE CREDITO]
      ,[VOLUME DE COMPRA]
      ,[PRIMEIRA COMPRA]
  FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES]

  SELECT * FROM [SUCOS_VENDAS].[dbo].[TABELA DE CLIENTES]

  SELECT [CPF]
  ,[NOME]
  FROM [TABELA DE CLIENTES]

  SELECT
  [NOME] AS CLIENTE
  ,[CPF] AS IDENTIFICADOR
  FROM [TABELA DE CLIENTES]

  SELECT
  [NOME],
  [MATRICULA]
  FROM [TABELA DE VENDEDORES]


  --FILTRANDO SELEÇÃO
  
SELECT * FROM [TABELA DE PRODUTOS]
--DELETE FROM [TABELA DE CLIENTES]PRODUTOS] WHERE [CODIGO DO PRODUTO]='1000889'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [CODIGO DO PRODUTO]='1000889'


SELECT * FROM [TABELA DE PRODUTOS]
WHERE [SABOR]='UVA'

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [SABOR]='LIMÃO'

DELETE FROM [TABELA DE PRODUTOS] WHERE [SABOR]='LIMÃO'

SELECT * FROM [TABELA DE VENDEDORES] WHERE NOME ='Cláudia Morais'


SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM='PET'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA]=4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA]>10

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA]<10

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA]<=4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA]>=4.555

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM='LATA'

SELECT * FROM [TABELA DE PRODUTOS] WHERE EMBALAGEM>'LATA'

SELECT * FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] <> 4.555

SELECT * FROM [TABELA DE VENDEDORES] WHERE [PERCENTUAL COMISSAO] > 0.1

SELECT * FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] = '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] > '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE [DATA DE NASCIMENTO] <= '1995-09-11'

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO])=1995

SELECT * FROM [TABELA DE CLIENTES] WHERE YEAR([DATA DE NASCIMENTO])<1995

SELECT * FROM [TABELA DE CLIENTES] WHERE MONTH([DATA DE NASCIMENTO])=9

SELECT * FROM [TABELA DE CLIENTES] WHERE DAY([DATA DE NASCIMENTO])=11

SELECT * FROM [TABELA DE VENDEDORES] WHERE YEAR([DATA ADMISSAO])>=2016